# Progressing error
MISSING_PIPELINE = "MISSING_PIPELINE"

# Text detection error
TEXT_NOT_FOUND = "TEXT_NOT_FOUND"
INVALID_TEXT_TYPE = "INVALID_TEXT_TYPE"

# Command error
COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND"
INVALID_COMMAND_PARAMS = "INVALID_COMMAND_PARAMS"

# Super resolution error
SR_MODEL_NOT_FOUND = "SR_MODEL_NOT_FOUND"

# Util error
INVALID_URI = "INVALID_URI"

# Parsing error
MISSING_SCRIPT = "MISSING_SCRIPT"
